### ISSUE TITLE
BrightData HTTPS proxy connection with Kameleo browser profile

### ISSUE THREAD

**Issue by Joshua901** [kameleo-io/local-api-client-typescript#1]
I m having issues connecting to my Bright Data DC proxy using kameleo.

```
.SetProxy("socks5", new Server("zproxy.lum-superproxy.io", 22225, "lum-customer-tinduong-zone-russiashared-ip-179.61.152.69", "pass"))
```
Is 22225 number the port number of the proxy?
If i want to run `https` instead of `socks5`, shall i just replace `socks5` with `https` then?

Kameleo starts the browser but all domains I'm visiting gets the connection refused error message. Keep getting this error:
**ERR_CONNECTION_ABORTED**

**Comment by kameleo-team** [comment]
Don't get confused based on our [example code](https://github.com/kameleo-io/local-api-examples/blob/master/nodejs/start_with_proxy/index.js). We only showcased how to use a SOCKS5 proxy. Actually, you can use HTTP, HTTPS, SOCKS5, and SSH proxies.

Instead of `socks5` type `http`. Not `https`. It will use the `https` protocol but to configure you have to type `http`

```
.SetProxy("http", new Server("zproxy.lum-superproxy.io", 22225, "lum-customer-tinduong-zone-russiashared-ip-179.61.152.69", "pass"))
```
